spring.application.name=workflow

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/workflow}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

workflow.worker-pool-size=4
workflow.poll-interval-ms=1000
workflow.lock-timeout-seconds=60
workflow.retry-poll-interval-ms=2000
workflow.timeout-watcher-interval-ms=5000

workflow.instance.id=${INSTANCE_ID:default}
workflow.instance.internal-url=${INSTANCE_INTERNAL_URL:}
workflow.instance.external-url=${INSTANCE_EXTERNAL_URL:}